spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
